### ISSUE TITLE
Parameter::explode type

### ISSUE THREAD

**Issue by DerManoMann** [djairhogeuens/openapi-php#6]
The `Parameter::explode` property is typed as `string` - however, the spec expects a `bool`.

It is also used both as string and bool in `PetstoreApi`

**Comment by djairhogeuens** [comment]
@DerManoMann this should be fixed as I removed the Explode class and just used a nullable boolean instead.

Note that I also removed the `DEFAULT` constants containing an empty string for the other enum classes and replaced the `string` type to `string|null` where they are used in order for the DEFAULT value to be represented by a `null` value instead of an empty string.
